### ISSUE TITLE
Image spacing is not retained in the downsampled version

### ISSUE THREAD

**Issue by SlicerMorph** [pieper/SlicerImageStacks#1]
After pointing out the full input stack, entering the original voxel spacing and choosing downsampling, the newly created downsampled volume does not retain the correct spacing (twice the enter valued), but 1x1x1mm

**Comment by pieper** [comment]
Hmm, the [logic looks right](https://github.com/pieper/SlicerImageStacks/blob/master/ImageStacks/ImageStacks.py#L304-L311).  If you're sure this is an issue I'll have a look after the New Year.
