### ISSUE TITLE
Can't paste numeric values to spacing if the pasted string is longer than the displayed value

### ISSUE THREAD

**Issue by muratmaga** [pieper/SlicerImageStacks#6]
For example I tried to paste 0.11339151446244 when the displayed value was 1.0000000mm and it didn't work. Cutting out the precision from the pasted value to 0.113391 make it work. But it is not clear to the user immediately (it appear as copy and paste doesn't work).

Perhaps trim (or round the value) to match the displayed precision. 

You can try with this data if you like:

https://www.morphosource.org/Detail/MediaDetail/Show/media_id/59060

**Comment by pieper** [comment]
Yes, that's odd behavior - probably just changing the number in the line linked below should fix it.  Can you try changing to 16 or even 20 to be on the safe side? 

https://github.com/pieper/SlicerImageStacks/blob/master/ImageStacks/ImageStacks.py#L110

**Comment by muratmaga** [comment]
I can try, and it will probably fix it, but since QT wants to display all those digits, it is a very ugly solution. And it also expands the module tab with to accommodate this internally (like the volume tab would be very wide as well).

**Comment by pieper** [comment]
After I checked in the Volumes module I saw that pasting this long string works there, so I copied over the modes that are set there.

I'll check this fix directly into SlicerMorph.
